### ISSUE TITLE
Taskbar size does not update after changing the system scaling

### ISSUE THREAD

**Issue by xoascf** [dremin/RetroBar#151]
The theme has to be changed manually to be updated, it is not automatic.

**Comment by dremin** [comment]
I'm not able to reproduce this, have you set any compatibility options on RetroBar.exe by chance?

**Comment by xoascf** [comment]
> 
> 
> I'm not able to reproduce this, have you set any compatibility options on RetroBar.exe by chance?

No compatibility options have been set.

In a clean installation of Windows 11, the taskbar does not update its size like the Properties window or the stock taskbar does.
Artifact from: https://github.com/dremin/RetroBar/actions/runs/1437230491

Stock taskbar behaviour:

https://user-images.githubusercontent.com/28744392/140845938-d1614a51-18ad-4f6e-ae46-e2099119757c.mp4

RetroBar behaviour:

https://user-images.githubusercontent.com/28744392/140846051-9fe4f8ff-0a82-4105-a660-fd8b1fbf5865.mp4

**Comment by dremin** [comment]
Thanks for the videos! Interesting, using the same settings as you I can reproduce this on Windows 11, but not Windows 10. I'll have to start debugging this further.

**Comment by dremin** [comment]
Okay, this is really strange. Windows doesn't send WM_DPICHANGED to the taskbar window for some reason, but it does if we change our size. I'm still working through trial and error to figure out what about the taskbar window causes this.

**Comment by xoascf** [comment]
Hey, check out this implementation:
https://github.com/PhilipRieck/WpfAppBar

It works fine for DPI changes in Windows 11, but everything else doesn't work as well as the ManagedShell implementation.

**Comment by dremin** [comment]
I am seeing DPI changes take effect again with Insider build 22581. However, I see #304 when that happens. Are you seeing the same?

**Comment by xoascf** [comment]
> I am seeing DPI changes take effect again with Insider build 22581. However, I see #304 when that happens. Are you seeing the same?

Interesting, the taskbar goes up and down in position when changing DPI and then down to the bottom edge of the screen, for some reason it worked for me to change the DPI with RetroBar at login (the taskbar was able to adapt to the selected DPI), but then it didn't (I downloaded and ran the new version).

**Comment by dremin** [comment]
@xoascf I believe this is fixed by #945 when changing DPI on the primary display, as doing that broadcasts a `TaskbarCreated` message.

**Comment by xoascf** [comment]
@dremin I just tried again on Windows 11, the last two Insider builds, both fail to change the scale for RetroBar, and still require reloading the parent or main theme.

Additional info: No tweaks enabled (no OpenGlass, no ExplorerBlurMica, no Windhawk, no StartAllBack, no patched styles, still the same).

https://github.com/user-attachments/assets/166a54a3-5548-452d-82d5-6c66c3d25fd0

**Comment by dremin** [comment]
@xoascf Oh well, thanks for testing! I wonder why my configuration is causing that message.

**Comment by yume-chan** [comment]
I found it's triggered by ManagedShell setting `WS_EX_TOOLWINDOW` style to the taskbar window: 

https://github.com/cairoshell/ManagedShell/blob/16ff1f312a79d81c8a3dc124f395b0bdc9a15f4f/src/ManagedShell.AppBar/AppBarWindow.cs#L311

https://github.com/cairoshell/ManagedShell/blob/6b9d5b85ffcd9d862581c5353d4c351a5236f9ba/src/ManagedShell.Common/Helpers/WindowHelper.cs#L105

There is a StackOverflow question without answers: https://stackoverflow.com/questions/77270061/window-wont-receive-wm-dpichanged-message-when-set-window-style-to-ws-ex-toolwi

---

https://stackoverflow.com/a/357598 seems to work, it creates another tool window as parent window, to hide the child window in Alt-Tab:

```patch
diff --git a/src/ManagedShell.AppBar/AppBarWindow.cs b/src/ManagedShell.AppBar/AppBarWindow.cs
index c8b9381..3099738 100644
--- a/src/ManagedShell.AppBar/AppBarWindow.cs
+++ b/src/ManagedShell.AppBar/AppBarWindow.cs
@@ -118,6 +118,17 @@ namespace ManagedShell.AppBar
 
         public AppBarWindow(AppBarManager appBarManager, ExplorerHelper explorerHelper, FullScreenHelper fullScreenHelper, AppBarScreen screen, AppBarEdge edge, AppBarMode mode, double size)
         {
+            Window fakeOwner = new Window();
+            fakeOwner.ShowInTaskbar = false;
+            fakeOwner.WindowStyle = WindowStyle.ToolWindow;
+            fakeOwner.Top = -10000;
+            fakeOwner.Left = -10000;
+            fakeOwner.Width = 1;
+            fakeOwner.Height = 1;
+            fakeOwner.Show();
+            Owner = fakeOwner;
+            fakeOwner.Hide();
+
             _explorerHelper = explorerHelper;
             _fullScreenHelper = fullScreenHelper;
             _appBarManager = appBarManager;
@@ -308,7 +319,7 @@ namespace ManagedShell.AppBar
             }
 
             // hide from alt-tab etc
-            WindowHelper.HideWindowFromTasks(Handle);
+            WindowHelper.ExcludeWindowFromPeek(Handle);
 
             // register for full-screen notifications
             _fullScreenHelper.FullScreenApps.CollectionChanged += FullScreenApps_CollectionChanged;
@@ -503,7 +514,7 @@ namespace ManagedShell.AppBar
                 ProcessScreenChange(ScreenSetupReason.DwmChange);
                 handled = true;
             }
-            
+
             return IntPtr.Zero;
         }
         #endregion
@@ -763,4 +774,4 @@ namespace ManagedShell.AppBar
         }
         #endregion
     }
-}
\ No newline at end of file
+}
```

https://github.com/user-attachments/assets/302d062f-1b63-4343-918a-a24e55fd17f9

---

Or maybe create another hidden window to receive DPI change events?

**Comment by dremin** [comment]
> I found it's triggered by ManagedShell setting `WS_EX_TOOLWINDOW` style to the taskbar window:

@yume-chan Thanks for figuring this out!

It looks like WPF's `ShowInTaskbar` property takes the hidden owner window approach, and we already set `ShowInTaskbar=true` in `AppBarWindow`, so we don't need the `WS_EX_TOOLWINDOW` style to hide from the taskbar. However, we do need that style to hide the window from Task Manager--I'm not aware of another way to achieve that. It seems like as long as the owner toolwindow is not visible, Task Manager will show the owned window.
